### ISSUE TITLE
Link to Crank, AdaptML, AnGST

### ISSUE THREAD

**Issue by albertyw** [albertyw/itolapi#8]

**Comment by etenjeh** [comment]
Warnings: []
Exporting to pdf
Traceback (most recent call last):
  File "example.py", line 72, in <module>
    itol_exporter.export('example_pdf.pdf')
  File "build/bdist.linux-x86_64/egg/itolapi/ItolExport.py", line 55, in export
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-13: ordinal not in range(128)

**Comment by etenjeh** [comment]
The above issue is what I have when running the ITOL example.py

**Comment by albertyw** [comment]
Should be fixed now
